server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9001
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MUB
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      max-file-size:
        20MB
      max-request-size:
        30MB
        
mybatis:
#  type-aliases-package: com.example.mub.model
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml